# Bioassessment Applications How To

```{r riverine setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

There are two bioassessment tools designed to assist biological staff with the assessment process. They include the [Bioassessment Dashboard](https://rconnect.deq.virginia.gov/IR2024bioassessmentDashboard/){target="_blank"} and the [Benthic Assessment Fact Sheet Tool](https://rconnect.deq.virginia.gov/BenthicAssessmentFactSheet/){target="_blank"}. Both tools are helpful throughout the bioassessment process, providing standardized data queries, visualizations, and analyses for biologists. The [CEDS Benthic Data Query Tool](https://rconnect.deq.virginia.gov/CEDSBenthicDataQueryTool/){target="_blank"} is a supplementary resource for more in depth benthic analyses, but that tool will not be discussed in depth in this chapter.

## General Bioassessment Workflow

After benthic macroinvertebrate data collection, processing, identification, and CEDS data entry, regional biological staff should assess all samples collected within a given Integrated Report window and provide station-level summaries to regional assessment staff. Biologists are best suited to make biological assessment decisions due to their expertise in benthic community structure and because they visited the sites and thus have personal knowledge of the site, watershed, and sampling conditions that might affect how data should be interpreted. 

Historically, biologists provided bioassessment decisions to regional assessment staff through individual bioassessment fact sheets. These one page documents summarize all benthic and habitat sampling data from a given site and are excellent resources for monitoring, assessment, and TMDL staff well after the fact sheet was written. Regional assessment staff rely on these fact sheets to relay expert interpretation of biological data readily into assessment decisions. These fact sheets improve communication between the monitoring and assessment arms of the programs and can help guide water planning efforts. However, these fact sheets were time consuming to create and difficult to keep track of during and after a given assessment cycle. 

With the adoption of more automated methods throughout the assessment process, regional biologists received two automated tools to standardize and expedite the bioassessment process. The [Bioassessment Dashboard](https://rconnect.deq.virginia.gov/IR2024bioassessmentDashboard/){target="_blank"} is intended as a first stop for biologists as they begin bioassessment in a given cycle. The tool identifies all biological and habitat data collected within a given assessment cycle, along with station-specific bioassessment information from previous assessment cycles, to readily assist with biological assessment decisions. This interactive tool performs all necessary data querying, manipulation along with interactive mapping, plotting, and tabular data summaries. 

When a station-level biological decision has been made, the regional biologists enter that decision and other metadata into a template [(download a copy of the template here)](https://covgov-my.sharepoint.com/:x:/g/personal/emma_jones_deq_virginia_gov/EcckR_eno0ZIiHTymTRmVy4BqPJIM4kAb5ZD3ACdNKeRAg?e=cG6yxA) {target="_blank"}. All fields must be completed in the template. When one or more bioassessment decisions are completed in the template, biologists may submit these decisions to be archived on the R server using the [Benthic Assessment Fact Sheet Tool](https://rconnect.deq.virginia.gov/BenthicAssessmentFactSheet/){target="_blank"}. This tool allows biologists to append their bioassessment decisions to a pinned dataset on the R server (with a point and click interface) and, once bioassessment decisions are pinned, they are able to generate and download a standardized biological fact sheet with the click of a button. There is no need to send these fact sheets to assessment staff and they have access to these fact sheets inside the  [Riverine Assessment Application](https://rconnect.deq.virginia.gov/IR2022riverineAssessmentApplication/){target="_blank"} as soon as the bioassessment data is pinned (archived) on the R server. 

## Bioassessment Dashboard How To
