--- 
title: "DEQ Water Quality Automated Assessment User Manual"
author: "Emma Jones and Kristen Bretz"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
# output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: openscapes/series
description: "A companion document describing the WQA automated assessment methodology."
split_by: "section"
---

# Introduction {#Introduction}

This manual serves as a companion document to DEQ's Water Quality Assessment (WQA) automated assessment methodology for completion of the biennial [305b/303d Integrated Report](https://www.deq.virginia.gov/water/water-quality/assessments/integrated-report). Virginia is among a handful of state agencies that have organized concerted efforts to systematically automate and expedite the water quality assessment process. These entities have all taken different approaches to best meet their state-specific analysis and reporting needs. Through the [Tools for Automated Data Assessment (TADA) working group](https://github.com/USEPA/TADA), EPA is organizing an effort to share code and create national tools to assist partners with assessment analyses. Considering the technological advances in water monitoring that have increased the quantity and types of data requiring consideration during an assessment period, as well as the static or decreasing staff time allocated to the assessment process, automation appears the only solution to keep up with Clean Water Act requirements and keep the public informed of the status of waterbody health and restoration timelines for those waterbodies not meeting water quality standards. By embracing automated assessment procedures, entities aim to provide constituents with higher quality, standardized, and transparent water quality assessment results while adhering to federally mandated deadlines. 

Virginia has taken a hybrid approach to the process of automating the water quality assessments. DEQ relies upon an automated process to manipulate hundreds of thousands of water quality data collected throughout the state during a given assessment period (six year window). These scripts evaluate each record for exceedances of appropriate Water Quality Standards. Regional assessment staff may use interactive web-based analytical tools provide more context to tabular results of exceedance analyses to assist with Quality Assurance/Quality Control (QA/QC) prior to submitting data to EPA's [Assessment, Total Maximum Daily Load (TMDL) Tracking and Implementation System (ATTAINS)](https://www.epa.gov/waterdata/attains) system through DEQ's internal [Comprehensive Environmental Data System (CEDS)](https://ceds.deq.virginia.gov/ui#). This approach maximizes the benefits of each partner in the assessment process, allowing computers to excel at systematic and expedited data manipulation and analysis at scale and allowing humans to digest multiple lines of evidence to identify any potential data collection or analysis errors or areas of environmental concern. 


## Project History{#ProjectHistory}

The agency began efforts toward automating components of the IR with a dissolved metals assessment written in SAS. These tabular results were provided to regional assessment staff along with raw data queries encompassing data stored in CEDS for each IR data window. 

The [Freshwater Probabilistic Monitoring](https://www.deq.virginia.gov/water/water-quality/monitoring/probabilistic-monitoring) program began automating analyses and a final report for inclusion in the 2016 IR using the open source [R programming language](https://cran.r-project.org/). These practices have been further refined each IR cycle, improving report quality and graphics as well as significantly reducing the amount of time required to generate a report after data collection. These methods were identified as a possible solution to the ongoing challenges in the WQA program to complete vast amounts of data analysis on increasingly short timelines with limited staff.

An effort to systematically analyze all water quality data stored in CEDS for assessments began in 2017. As a pilot project, lakes and reservoirs in the Blue Ridge Regional Office (BRRO) assessment region were selected for first waterbody type to undergo automation and receive an interactive web-based tool to assist regional assessment staff for the 2018 IR. These initial automated assessment efforts were completed using the open source [R programming language](https://cran.r-project.org/) and interactive applications were built using the [Shiny](https://shiny.rstudio.com/) package. Rivers and streams followed suit for the 2020 IR, joining lacustrine waterbodies with automated assessment methods and interactive assessment tools. The 2020 IR automated methods were scaled from just the BRRO region to statewide applicability. A pilot project to incorporate citizen monitoring data requiring assessment was undertaken in the BRRO assessment region for the 2020 IR. This pilot proved effective in standardizing and increasing efficiency of incorporating this disparate data and was officially adopted as a process for future IR windows. 

After thorough QA from regional assessment staff across the state, the riverine and lacustrine automated assessment tools were rebooted for the 2022 IR with increased functionality and the ability to assess more parameters, including those not stored in CEDS. However, due to delays organizing citizen monitoring data statewide, automated results for these data were not provided for the 2022 IR. A new database schema for archiving station-specific water quality standards and assessment unit information was implemented. This system benefited the assessment process as well as numerous DEQ water programs that previously did not have access to WQS information at that spatial scale. Appendices and fact sheets for the IR were generated using R and [Rmarkdown](https://rmarkdown.rstudio.com/) for the first time during the 2022 IR. 

The 2024 IR further refines improvements to the riverine and lacustrine automated assessment methods and interactive tools. By partnering with the [Chesapeake Monitoring Cooperative (CMC)](https://www.allianceforthebay.org/project/chesapeake-monitoring-cooperative/), DEQ leveraged an existing public-facing citizen monitoring data portal to expand utility outside the Chesapeake Bay watershed and incorporate all of Virginia's citizen monitoring data. These data are now automatically cleaned and stored by the CMC and can more easily be incorporated in the automated assessment process with web scraping techniques.

To date, no estuarine-specific assessment methods have been completed, but the WQA program is investigating utility and potential adoption among regions with estuarine waters.



## Acknowledgements {#Acknowledgements}

Many WQA and Water Quality Standards (WQA) staff have contributed to this effort:

* Kristen Bretz (kristen.bretz@deq.virginia.gov)
* Jason Hill (jason.hill@deq.virginia.gov)
* Sandy Mueller (sandra.mueller@deq.virginia.gov)
* Cleo Baker (cleo.baker@deq.virginia.gov)
* Amanda Shaver (amanda.shaver@deq.virginia.gov)
* Tish Robertson (tish.robertson@deq.virginia.gov)
* Paula Main (paula.main@deq.virginia.gov)
* Mary Dail (mary.dail@deq.virginia.gov)
* Martha Chapman (martha.chapman@deq.virginia.gov)
* Sara Jordan (sara.jordan@deq.virginia.gov)
* Kristie Britt (kristie.britt@deq.virginia.gov)
* Jennifer Palmore (jennifer.palmore@deq.virginia.gov)
* Kelley West (kelley.west@deq.virginia.gov)
* Rebecca Shoemaker (rebecca.shoemaker@deq.virginia.gov)



Please direct any project questions to Emma Jones (emma.jones@deq.virginia.gov). 