# Riverine Application How To

```{r riverine setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The [Riverine Assessment App](https://rconnect.deq.virginia.gov/IR2024riverineAssessmentApp/) is located on the R server. **The linked version of the application is in draft development stage with DRAFT DATA until after the data solicitation deadline and final product release. Expect this release in late April 2023.**

The purpose of this tool is to expand upon the Station Table summary provided by the automated assessment methodology. A single parameter summary (or in the case of metals, toxics, etc. a single summary of multiple parameters) does not do justice to the data analyzed by the automated assessment process. The Riverine Assessment App provides an interactive data analysis experience to improve users' understanding of automated assessment analyses and decisions. The intended audience is any DEQ employee from regional assessors and field staff, to managers, providing better data understanding through interactive data visualizations, descriptive standard application and WQA guidance explanations, and statewide applicability. 

A notable benefit of these standardized tools is the increased accessibility of assessment decisions. No longer are assessment tools limited to regional assessment staff, resulting in bottlenecks when assessment questions arise. These self-service tools articulate assessment procedures to guide data and decision discussions across multiple end users. 

This tool is a companion to the Station Table throughout the decision-making process the regional assessment staff sustain as data is entered into WQA CEDS. The next sections will detail typical workflow procedures to using this tool for data exploration and/or assessment. 

## Application Orientation

This application brings station-level automated analyses provided in the Station Table to life through interactive data visualizations, maps, and tables. The tool is divided into three tabs that must be visited sequentially for proper application functionality. The `Data Upload` tab provides a basic overview of application data sources, provides download of the statewide Station Table resultant from previous automated assessment procedures, and requires upload of either the default Station Table or a custom Station Table (e.g. the Station Table filtered to a specific region). The `Watershed Selection` tab allows further investigation of particular assessment watersheds (VAHU6) by assessment region and major basin. This tab offers high level summaries of stations within a chosen assessment watershed as well as detailed exceedance summaries across assessment units through tools embedded in modal windows. The `Assessment Unit Review` tab dives into all assessment units and stations contained within a selected assessment watershed. By drilling down from watershed to assessment unit to station, users may explore assessment data against applicable Water Quality Standards and criteria to better understand how assessment guidance leads assessment staff to appropriate decisions across designated uses. Previous assessment decisions are provided along with all centrally stored assessment data to provide a full picture of stations that require addressing during a given assessment cycle.